/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPatrimonioRouteImport } from './routes/app.patrimonio'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEscalasRouteImport } from './routes/app.escalas'
import { Route as AppEbdRouteImport } from './routes/app.ebd'
import { Route as AppDepartmentsRouteImport } from './routes/app.departments'
import { Route as AppConvocacoesRouteImport } from './routes/app.convocacoes'
import { Route as AppConselhoFiscalRouteImport } from './routes/app.conselho-fiscal'
import { Route as AppComprasRouteImport } from './routes/app.compras'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAtasRouteImport } from './routes/app.atas'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AppMembersIndexRouteImport } from './routes/app.members.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/app.financeiro.index'
import { Route as AppEbdIndexRouteImport } from './routes/app.ebd.index'
import { Route as AppCheckinIndexRouteImport } from './routes/app.checkin.index'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as AppMembersNewRouteImport } from './routes/app.members.new'
import { Route as AppMembersIdRouteImport } from './routes/app.members.$id'
import { Route as AppFinanceiroRelatoriosRouteImport } from './routes/app.financeiro.relatorios'
import { Route as AppFinanceiroContasRouteImport } from './routes/app.financeiro.contas'
import { Route as AppFinanceiroCentrosRouteImport } from './routes/app.financeiro.centros'
import { Route as AppEbdClassIdRouteImport } from './routes/app.ebd.$classId'
import { Route as AppCheckinScheduleIdRouteImport } from './routes/app.checkin.$scheduleId'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'
import { Route as AppMembersIdEditRouteImport } from './routes/app.members.$id.edit'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPatrimonioRoute = AppPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasRoute = AppEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AppRoute,
} as any)
const AppEbdRoute = AppEbdRouteImport.update({
  id: '/ebd',
  path: '/ebd',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppConvocacoesRoute = AppConvocacoesRouteImport.update({
  id: '/convocacoes',
  path: '/convocacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConselhoFiscalRoute = AppConselhoFiscalRouteImport.update({
  id: '/conselho-fiscal',
  path: '/conselho-fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAtasRoute = AppAtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => AppRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppEbdIndexRoute = AppEbdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEbdRoute,
} as any)
const AppCheckinIndexRoute = AppCheckinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCheckinRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const AppMembersNewRoute = AppMembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppMembersIdRoute = AppMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppFinanceiroRelatoriosRoute = AppFinanceiroRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroContasRoute = AppFinanceiroContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCentrosRoute = AppFinanceiroCentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppEbdClassIdRoute = AppEbdClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => AppEbdRoute,
} as any)
const AppCheckinScheduleIdRoute = AppCheckinScheduleIdRouteImport.update({
  id: '/$scheduleId',
  path: '/$scheduleId',
  getParentRoute: () => AppCheckinRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const AppMembersIdEditRoute = AppMembersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppMembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/select-tenant': typeof SelectTenantRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/app/atas': typeof AppAtasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/compras': typeof AppComprasRoute
  '/app/conselho-fiscal': typeof AppConselhoFiscalRoute
  '/app/convocacoes': typeof AppConvocacoesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/ebd': typeof AppEbdRouteWithChildren
  '/app/escalas': typeof AppEscalasRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/profile': typeof AppProfileRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/settings': typeof AppSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/app/checkin/$scheduleId': typeof AppCheckinScheduleIdRoute
  '/app/ebd/$classId': typeof AppEbdClassIdRoute
  '/app/financeiro/centros': typeof AppFinanceiroCentrosRoute
  '/app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/app/financeiro/relatorios': typeof AppFinanceiroRelatoriosRoute
  '/app/members/$id': typeof AppMembersIdRouteWithChildren
  '/app/members/new': typeof AppMembersNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/app/checkin/': typeof AppCheckinIndexRoute
  '/app/ebd/': typeof AppEbdIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/members/$id/edit': typeof AppMembersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/select-tenant': typeof SelectTenantRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/atas': typeof AppAtasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/compras': typeof AppComprasRoute
  '/app/conselho-fiscal': typeof AppConselhoFiscalRoute
  '/app/convocacoes': typeof AppConvocacoesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/profile': typeof AppProfileRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/settings': typeof AppSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/app/checkin/$scheduleId': typeof AppCheckinScheduleIdRoute
  '/app/ebd/$classId': typeof AppEbdClassIdRoute
  '/app/financeiro/centros': typeof AppFinanceiroCentrosRoute
  '/app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/app/financeiro/relatorios': typeof AppFinanceiroRelatoriosRoute
  '/app/members/$id': typeof AppMembersIdRouteWithChildren
  '/app/members/new': typeof AppMembersNewRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/app/checkin': typeof AppCheckinIndexRoute
  '/app/ebd': typeof AppEbdIndexRoute
  '/app/financeiro': typeof AppFinanceiroIndexRoute
  '/app/members': typeof AppMembersIndexRoute
  '/app/members/$id/edit': typeof AppMembersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/select-tenant': typeof SelectTenantRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/app/atas': typeof AppAtasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/compras': typeof AppComprasRoute
  '/app/conselho-fiscal': typeof AppConselhoFiscalRoute
  '/app/convocacoes': typeof AppConvocacoesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/ebd': typeof AppEbdRouteWithChildren
  '/app/escalas': typeof AppEscalasRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/profile': typeof AppProfileRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/settings': typeof AppSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/app/checkin/$scheduleId': typeof AppCheckinScheduleIdRoute
  '/app/ebd/$classId': typeof AppEbdClassIdRoute
  '/app/financeiro/centros': typeof AppFinanceiroCentrosRoute
  '/app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/app/financeiro/relatorios': typeof AppFinanceiroRelatoriosRoute
  '/app/members/$id': typeof AppMembersIdRouteWithChildren
  '/app/members/new': typeof AppMembersNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/app/checkin/': typeof AppCheckinIndexRoute
  '/app/ebd/': typeof AppEbdIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/members/$id/edit': typeof AppMembersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/register'
    | '/select-tenant'
    | '/admin/admins'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/atas'
    | '/app/auditoria'
    | '/app/checkin'
    | '/app/compras'
    | '/app/conselho-fiscal'
    | '/app/convocacoes'
    | '/app/departments'
    | '/app/ebd'
    | '/app/escalas'
    | '/app/financeiro'
    | '/app/members'
    | '/app/notificacoes'
    | '/app/patrimonio'
    | '/app/profile'
    | '/app/relatorios'
    | '/app/settings'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$id'
    | '/app/checkin/$scheduleId'
    | '/app/ebd/$classId'
    | '/app/financeiro/centros'
    | '/app/financeiro/contas'
    | '/app/financeiro/relatorios'
    | '/app/members/$id'
    | '/app/members/new'
    | '/admin/tenants/'
    | '/app/checkin/'
    | '/app/ebd/'
    | '/app/financeiro/'
    | '/app/members/'
    | '/app/members/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/register'
    | '/select-tenant'
    | '/admin/admins'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/plans'
    | '/admin/settings'
    | '/app/atas'
    | '/app/auditoria'
    | '/app/compras'
    | '/app/conselho-fiscal'
    | '/app/convocacoes'
    | '/app/departments'
    | '/app/escalas'
    | '/app/notificacoes'
    | '/app/patrimonio'
    | '/app/profile'
    | '/app/relatorios'
    | '/app/settings'
    | '/admin'
    | '/app'
    | '/admin/tenants/$id'
    | '/app/checkin/$scheduleId'
    | '/app/ebd/$classId'
    | '/app/financeiro/centros'
    | '/app/financeiro/contas'
    | '/app/financeiro/relatorios'
    | '/app/members/$id'
    | '/app/members/new'
    | '/admin/tenants'
    | '/app/checkin'
    | '/app/ebd'
    | '/app/financeiro'
    | '/app/members'
    | '/app/members/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/register'
    | '/select-tenant'
    | '/admin/admins'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/atas'
    | '/app/auditoria'
    | '/app/checkin'
    | '/app/compras'
    | '/app/conselho-fiscal'
    | '/app/convocacoes'
    | '/app/departments'
    | '/app/ebd'
    | '/app/escalas'
    | '/app/financeiro'
    | '/app/members'
    | '/app/notificacoes'
    | '/app/patrimonio'
    | '/app/profile'
    | '/app/relatorios'
    | '/app/settings'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$id'
    | '/app/checkin/$scheduleId'
    | '/app/ebd/$classId'
    | '/app/financeiro/centros'
    | '/app/financeiro/contas'
    | '/app/financeiro/relatorios'
    | '/app/members/$id'
    | '/app/members/new'
    | '/admin/tenants/'
    | '/app/checkin/'
    | '/app/ebd/'
    | '/app/financeiro/'
    | '/app/members/'
    | '/app/members/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SelectTenantRoute: typeof SelectTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patrimonio': {
      id: '/app/patrimonio'
      path: '/patrimonio'
      fullPath: '/app/patrimonio'
      preLoaderRoute: typeof AppPatrimonioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escalas': {
      id: '/app/escalas'
      path: '/escalas'
      fullPath: '/app/escalas'
      preLoaderRoute: typeof AppEscalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ebd': {
      id: '/app/ebd'
      path: '/ebd'
      fullPath: '/app/ebd'
      preLoaderRoute: typeof AppEbdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/convocacoes': {
      id: '/app/convocacoes'
      path: '/convocacoes'
      fullPath: '/app/convocacoes'
      preLoaderRoute: typeof AppConvocacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conselho-fiscal': {
      id: '/app/conselho-fiscal'
      path: '/conselho-fiscal'
      fullPath: '/app/conselho-fiscal'
      preLoaderRoute: typeof AppConselhoFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compras': {
      id: '/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atas': {
      id: '/app/atas'
      path: '/atas'
      fullPath: '/app/atas'
      preLoaderRoute: typeof AppAtasRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/members/': {
      id: '/app/members/'
      path: '/'
      fullPath: '/app/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/financeiro/': {
      id: '/app/financeiro/'
      path: '/'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/ebd/': {
      id: '/app/ebd/'
      path: '/'
      fullPath: '/app/ebd/'
      preLoaderRoute: typeof AppEbdIndexRouteImport
      parentRoute: typeof AppEbdRoute
    }
    '/app/checkin/': {
      id: '/app/checkin/'
      path: '/'
      fullPath: '/app/checkin/'
      preLoaderRoute: typeof AppCheckinIndexRouteImport
      parentRoute: typeof AppCheckinRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/app/members/new': {
      id: '/app/members/new'
      path: '/new'
      fullPath: '/app/members/new'
      preLoaderRoute: typeof AppMembersNewRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/members/$id': {
      id: '/app/members/$id'
      path: '/$id'
      fullPath: '/app/members/$id'
      preLoaderRoute: typeof AppMembersIdRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/financeiro/relatorios': {
      id: '/app/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/app/financeiro/relatorios'
      preLoaderRoute: typeof AppFinanceiroRelatoriosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/contas': {
      id: '/app/financeiro/contas'
      path: '/contas'
      fullPath: '/app/financeiro/contas'
      preLoaderRoute: typeof AppFinanceiroContasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/centros': {
      id: '/app/financeiro/centros'
      path: '/centros'
      fullPath: '/app/financeiro/centros'
      preLoaderRoute: typeof AppFinanceiroCentrosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/ebd/$classId': {
      id: '/app/ebd/$classId'
      path: '/$classId'
      fullPath: '/app/ebd/$classId'
      preLoaderRoute: typeof AppEbdClassIdRouteImport
      parentRoute: typeof AppEbdRoute
    }
    '/app/checkin/$scheduleId': {
      id: '/app/checkin/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/app/checkin/$scheduleId'
      preLoaderRoute: typeof AppCheckinScheduleIdRouteImport
      parentRoute: typeof AppCheckinRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/app/members/$id/edit': {
      id: '/app/members/$id/edit'
      path: '/edit'
      fullPath: '/app/members/$id/edit'
      preLoaderRoute: typeof AppMembersIdEditRouteImport
      parentRoute: typeof AppMembersIdRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCheckinRouteChildren {
  AppCheckinScheduleIdRoute: typeof AppCheckinScheduleIdRoute
  AppCheckinIndexRoute: typeof AppCheckinIndexRoute
}

const AppCheckinRouteChildren: AppCheckinRouteChildren = {
  AppCheckinScheduleIdRoute: AppCheckinScheduleIdRoute,
  AppCheckinIndexRoute: AppCheckinIndexRoute,
}

const AppCheckinRouteWithChildren = AppCheckinRoute._addFileChildren(
  AppCheckinRouteChildren,
)

interface AppEbdRouteChildren {
  AppEbdClassIdRoute: typeof AppEbdClassIdRoute
  AppEbdIndexRoute: typeof AppEbdIndexRoute
}

const AppEbdRouteChildren: AppEbdRouteChildren = {
  AppEbdClassIdRoute: AppEbdClassIdRoute,
  AppEbdIndexRoute: AppEbdIndexRoute,
}

const AppEbdRouteWithChildren =
  AppEbdRoute._addFileChildren(AppEbdRouteChildren)

interface AppFinanceiroRouteChildren {
  AppFinanceiroCentrosRoute: typeof AppFinanceiroCentrosRoute
  AppFinanceiroContasRoute: typeof AppFinanceiroContasRoute
  AppFinanceiroRelatoriosRoute: typeof AppFinanceiroRelatoriosRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCentrosRoute: AppFinanceiroCentrosRoute,
  AppFinanceiroContasRoute: AppFinanceiroContasRoute,
  AppFinanceiroRelatoriosRoute: AppFinanceiroRelatoriosRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppMembersIdRouteChildren {
  AppMembersIdEditRoute: typeof AppMembersIdEditRoute
}

const AppMembersIdRouteChildren: AppMembersIdRouteChildren = {
  AppMembersIdEditRoute: AppMembersIdEditRoute,
}

const AppMembersIdRouteWithChildren = AppMembersIdRoute._addFileChildren(
  AppMembersIdRouteChildren,
)

interface AppMembersRouteChildren {
  AppMembersIdRoute: typeof AppMembersIdRouteWithChildren
  AppMembersNewRoute: typeof AppMembersNewRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
}

const AppMembersRouteChildren: AppMembersRouteChildren = {
  AppMembersIdRoute: AppMembersIdRouteWithChildren,
  AppMembersNewRoute: AppMembersNewRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
}

const AppMembersRouteWithChildren = AppMembersRoute._addFileChildren(
  AppMembersRouteChildren,
)

interface AppRouteChildren {
  AppAtasRoute: typeof AppAtasRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCheckinRoute: typeof AppCheckinRouteWithChildren
  AppComprasRoute: typeof AppComprasRoute
  AppConselhoFiscalRoute: typeof AppConselhoFiscalRoute
  AppConvocacoesRoute: typeof AppConvocacoesRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppEbdRoute: typeof AppEbdRouteWithChildren
  AppEscalasRoute: typeof AppEscalasRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppMembersRoute: typeof AppMembersRouteWithChildren
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPatrimonioRoute: typeof AppPatrimonioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtasRoute: AppAtasRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCheckinRoute: AppCheckinRouteWithChildren,
  AppComprasRoute: AppComprasRoute,
  AppConselhoFiscalRoute: AppConselhoFiscalRoute,
  AppConvocacoesRoute: AppConvocacoesRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppEbdRoute: AppEbdRouteWithChildren,
  AppEscalasRoute: AppEscalasRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppMembersRoute: AppMembersRouteWithChildren,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPatrimonioRoute: AppPatrimonioRoute,
  AppProfileRoute: AppProfileRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SelectTenantRoute: SelectTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
