/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPatrimonioRouteImport } from './routes/app.patrimonio'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEscalasRouteImport } from './routes/app.escalas'
import { Route as AppDepartmentsRouteImport } from './routes/app.departments'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppAtasRouteImport } from './routes/app.atas'
import { Route as AppMembersIndexRouteImport } from './routes/app.members.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/app.financeiro.index'
import { Route as AppCheckinIndexRouteImport } from './routes/app.checkin.index'
import { Route as AppMembersNewRouteImport } from './routes/app.members.new'
import { Route as AppMembersIdRouteImport } from './routes/app.members.$id'
import { Route as AppFinanceiroRelatoriosRouteImport } from './routes/app.financeiro.relatorios'
import { Route as AppFinanceiroContasRouteImport } from './routes/app.financeiro.contas'
import { Route as AppFinanceiroCentrosRouteImport } from './routes/app.financeiro.centros'
import { Route as AppCheckinScheduleIdRouteImport } from './routes/app.checkin.$scheduleId'
import { Route as AppMembersIdEditRouteImport } from './routes/app.members.$id.edit'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPatrimonioRoute = AppPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasRoute = AppEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppAtasRoute = AppAtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppCheckinIndexRoute = AppCheckinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCheckinRoute,
} as any)
const AppMembersNewRoute = AppMembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppMembersIdRoute = AppMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppFinanceiroRelatoriosRoute = AppFinanceiroRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroContasRoute = AppFinanceiroContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCentrosRoute = AppFinanceiroCentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppCheckinScheduleIdRoute = AppCheckinScheduleIdRouteImport.update({
  id: '/$scheduleId',
  path: '/$scheduleId',
  getParentRoute: () => AppCheckinRoute,
} as any)
const AppMembersIdEditRoute = AppMembersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppMembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/select-tenant': typeof SelectTenantRoute
  '/app/atas': typeof AppAtasRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/departments': typeof AppDepartmentsRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/checkin/$scheduleId': typeof AppCheckinScheduleIdRoute
  '/app/financeiro/centros': typeof AppFinanceiroCentrosRoute
  '/app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/app/financeiro/relatorios': typeof AppFinanceiroRelatoriosRoute
  '/app/members/$id': typeof AppMembersIdRouteWithChildren
  '/app/members/new': typeof AppMembersNewRoute
  '/app/checkin/': typeof AppCheckinIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/members/$id/edit': typeof AppMembersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/select-tenant': typeof SelectTenantRoute
  '/app/atas': typeof AppAtasRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/checkin/$scheduleId': typeof AppCheckinScheduleIdRoute
  '/app/financeiro/centros': typeof AppFinanceiroCentrosRoute
  '/app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/app/financeiro/relatorios': typeof AppFinanceiroRelatoriosRoute
  '/app/members/$id': typeof AppMembersIdRouteWithChildren
  '/app/members/new': typeof AppMembersNewRoute
  '/app/checkin': typeof AppCheckinIndexRoute
  '/app/financeiro': typeof AppFinanceiroIndexRoute
  '/app/members': typeof AppMembersIndexRoute
  '/app/members/$id/edit': typeof AppMembersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/select-tenant': typeof SelectTenantRoute
  '/app/atas': typeof AppAtasRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/departments': typeof AppDepartmentsRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/patrimonio': typeof AppPatrimonioRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/checkin/$scheduleId': typeof AppCheckinScheduleIdRoute
  '/app/financeiro/centros': typeof AppFinanceiroCentrosRoute
  '/app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/app/financeiro/relatorios': typeof AppFinanceiroRelatoriosRoute
  '/app/members/$id': typeof AppMembersIdRouteWithChildren
  '/app/members/new': typeof AppMembersNewRoute
  '/app/checkin/': typeof AppCheckinIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/members/$id/edit': typeof AppMembersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/register'
    | '/select-tenant'
    | '/app/atas'
    | '/app/checkin'
    | '/app/departments'
    | '/app/escalas'
    | '/app/financeiro'
    | '/app/members'
    | '/app/patrimonio'
    | '/app/relatorios'
    | '/app/settings'
    | '/app/'
    | '/app/checkin/$scheduleId'
    | '/app/financeiro/centros'
    | '/app/financeiro/contas'
    | '/app/financeiro/relatorios'
    | '/app/members/$id'
    | '/app/members/new'
    | '/app/checkin/'
    | '/app/financeiro/'
    | '/app/members/'
    | '/app/members/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/register'
    | '/select-tenant'
    | '/app/atas'
    | '/app/departments'
    | '/app/escalas'
    | '/app/patrimonio'
    | '/app/relatorios'
    | '/app/settings'
    | '/app'
    | '/app/checkin/$scheduleId'
    | '/app/financeiro/centros'
    | '/app/financeiro/contas'
    | '/app/financeiro/relatorios'
    | '/app/members/$id'
    | '/app/members/new'
    | '/app/checkin'
    | '/app/financeiro'
    | '/app/members'
    | '/app/members/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/register'
    | '/select-tenant'
    | '/app/atas'
    | '/app/checkin'
    | '/app/departments'
    | '/app/escalas'
    | '/app/financeiro'
    | '/app/members'
    | '/app/patrimonio'
    | '/app/relatorios'
    | '/app/settings'
    | '/app/'
    | '/app/checkin/$scheduleId'
    | '/app/financeiro/centros'
    | '/app/financeiro/contas'
    | '/app/financeiro/relatorios'
    | '/app/members/$id'
    | '/app/members/new'
    | '/app/checkin/'
    | '/app/financeiro/'
    | '/app/members/'
    | '/app/members/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SelectTenantRoute: typeof SelectTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patrimonio': {
      id: '/app/patrimonio'
      path: '/patrimonio'
      fullPath: '/app/patrimonio'
      preLoaderRoute: typeof AppPatrimonioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escalas': {
      id: '/app/escalas'
      path: '/escalas'
      fullPath: '/app/escalas'
      preLoaderRoute: typeof AppEscalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atas': {
      id: '/app/atas'
      path: '/atas'
      fullPath: '/app/atas'
      preLoaderRoute: typeof AppAtasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members/': {
      id: '/app/members/'
      path: '/'
      fullPath: '/app/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/financeiro/': {
      id: '/app/financeiro/'
      path: '/'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/checkin/': {
      id: '/app/checkin/'
      path: '/'
      fullPath: '/app/checkin/'
      preLoaderRoute: typeof AppCheckinIndexRouteImport
      parentRoute: typeof AppCheckinRoute
    }
    '/app/members/new': {
      id: '/app/members/new'
      path: '/new'
      fullPath: '/app/members/new'
      preLoaderRoute: typeof AppMembersNewRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/members/$id': {
      id: '/app/members/$id'
      path: '/$id'
      fullPath: '/app/members/$id'
      preLoaderRoute: typeof AppMembersIdRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/financeiro/relatorios': {
      id: '/app/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/app/financeiro/relatorios'
      preLoaderRoute: typeof AppFinanceiroRelatoriosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/contas': {
      id: '/app/financeiro/contas'
      path: '/contas'
      fullPath: '/app/financeiro/contas'
      preLoaderRoute: typeof AppFinanceiroContasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/centros': {
      id: '/app/financeiro/centros'
      path: '/centros'
      fullPath: '/app/financeiro/centros'
      preLoaderRoute: typeof AppFinanceiroCentrosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/checkin/$scheduleId': {
      id: '/app/checkin/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/app/checkin/$scheduleId'
      preLoaderRoute: typeof AppCheckinScheduleIdRouteImport
      parentRoute: typeof AppCheckinRoute
    }
    '/app/members/$id/edit': {
      id: '/app/members/$id/edit'
      path: '/edit'
      fullPath: '/app/members/$id/edit'
      preLoaderRoute: typeof AppMembersIdEditRouteImport
      parentRoute: typeof AppMembersIdRoute
    }
  }
}

interface AppCheckinRouteChildren {
  AppCheckinScheduleIdRoute: typeof AppCheckinScheduleIdRoute
  AppCheckinIndexRoute: typeof AppCheckinIndexRoute
}

const AppCheckinRouteChildren: AppCheckinRouteChildren = {
  AppCheckinScheduleIdRoute: AppCheckinScheduleIdRoute,
  AppCheckinIndexRoute: AppCheckinIndexRoute,
}

const AppCheckinRouteWithChildren = AppCheckinRoute._addFileChildren(
  AppCheckinRouteChildren,
)

interface AppFinanceiroRouteChildren {
  AppFinanceiroCentrosRoute: typeof AppFinanceiroCentrosRoute
  AppFinanceiroContasRoute: typeof AppFinanceiroContasRoute
  AppFinanceiroRelatoriosRoute: typeof AppFinanceiroRelatoriosRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCentrosRoute: AppFinanceiroCentrosRoute,
  AppFinanceiroContasRoute: AppFinanceiroContasRoute,
  AppFinanceiroRelatoriosRoute: AppFinanceiroRelatoriosRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppMembersIdRouteChildren {
  AppMembersIdEditRoute: typeof AppMembersIdEditRoute
}

const AppMembersIdRouteChildren: AppMembersIdRouteChildren = {
  AppMembersIdEditRoute: AppMembersIdEditRoute,
}

const AppMembersIdRouteWithChildren = AppMembersIdRoute._addFileChildren(
  AppMembersIdRouteChildren,
)

interface AppMembersRouteChildren {
  AppMembersIdRoute: typeof AppMembersIdRouteWithChildren
  AppMembersNewRoute: typeof AppMembersNewRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
}

const AppMembersRouteChildren: AppMembersRouteChildren = {
  AppMembersIdRoute: AppMembersIdRouteWithChildren,
  AppMembersNewRoute: AppMembersNewRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
}

const AppMembersRouteWithChildren = AppMembersRoute._addFileChildren(
  AppMembersRouteChildren,
)

interface AppRouteChildren {
  AppAtasRoute: typeof AppAtasRoute
  AppCheckinRoute: typeof AppCheckinRouteWithChildren
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppEscalasRoute: typeof AppEscalasRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppMembersRoute: typeof AppMembersRouteWithChildren
  AppPatrimonioRoute: typeof AppPatrimonioRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtasRoute: AppAtasRoute,
  AppCheckinRoute: AppCheckinRouteWithChildren,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppEscalasRoute: AppEscalasRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppMembersRoute: AppMembersRouteWithChildren,
  AppPatrimonioRoute: AppPatrimonioRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SelectTenantRoute: SelectTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
